# Generated by Django 4.2.30 on 2026-07-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dori', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['-created_at'], 'verbose_name': 'Drug', 'verbose_name_plural': 'Drugs'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='fabric',
            field=models.CharField(max_length=50),
        ),
    ]
